# Arquivo de configuração para o Render - render.yaml
services:
  - type: web
    name: api-wheels
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/project-api-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        fromDatabase:
          name: nome-do-seu-banco-aqui
          property: connectionString
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
